// vue/Counter.vue
<template>
    <div>
        <h1>Counter: {{ count }}</h1>
        <button @click="increment">+</button>
        <button @click="decrement">-</button>
    </div>
</template>

<script>
export default {
    data() {
        return {
            count: 0,
        };
    },
    methods: {
        increment() {
            this.count += 1;
        },
        decrement() {
            this.count -= 1;
        }
    }
}
</script>

// react/Counter.js
import React, { useState } from 'react';

export default () => {

    const [count, setCount] = useState(0);

    function increment() {
        setCount(count + 1);
    }

    function decrement() {
        setCount(count - 1);
    }
    
    return <>
        <h1>Counter: {count}</h1>
        <button onClick={ increment }>+</button>
        <button onClick={ decrement }>-</button>
    </>
}
