// react/Counter.js
import React, { useState } from 'react';

export default () => {

    const [count, setCount] = useState(0);

    function increment() {
        setCount(count + 1);
    }

    function decrement() {
        setCount(count - 1);
    }
    
    return <>
        <h1>Counter: {count}</h1>
        <button onClick={ increment }>+</button>
        <button onClick={ decrement }>-</button>
    </>
}

// angular/counter.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-counter',
  templateUrl: './counter.component.html'
})
export class CounterComponent {
  count = 0;
  increment() {
    this.count += 1;
  }

  decrement() {
    this.count -= 1;
  }
}

<h1>Counter: {{ count }}</h1>
<button (click)="increment()">+</button>
<button (click)="decrement()">-</button>
